name: push events
on: 
  schedule:
    - cron: '*/5 * * * *'  #Runs every 5 minutes.
    
jobs:
  show_info:
    runs-on: ubuntu-latest
    steps:
      - name: info
        run: |
              echo "this is push event on all branches"
