name: manual workflow
on: 
  workflow_dispatch:
    inputs: 
      ENV:
        description: ENV NAME
        default: hi
    
jobs:
  show_info:
    runs-on: ubuntu-latest
    steps:
      - name: info
        run: |
              echo "ENV = ${{ github.event.inputs.ENV }}"
